### ISSUE TITLE
[next-auth]: `useSession` must be wrapped in a <SessionProvider /> in the _app.js file

### ISSUE THREAD

**Issue by aimiisme** [KSU-Google-DSC/Webapp#81]
Imported `DashboardMenu` into `_app.js`. The `DashboardMenu` works the same as the regular `Navbar`, except that `DashboardMenu` will be displayed only after redirecting to Dashboard.
The error occurred under the commits [b6dce64] and the branch `feature/add_dashboard`. I think the error is relevant to the `next-auth` setup and configuration.
<h3> Error Screenshot </h3>
<img width="958" alt="Screen Shot 2023-01-10 at 1 30 46 PM" src="https://user-images.githubusercontent.com/90480687/211633245-fc58d5a0-d116-4e36-9375-b599a6fa2148.png">

**Comment by Sanjay-B** [comment]
Sorry for the late response. Looked into this issue. We had issues in the past with next-auth because we were using two firebase versions that seemed to be incompatible to the default indexed name that next-auth was using by default. @johnnymcmike & I had this long late night discussion over this a while back. I created PR a while back that addresses this issue directly, but, unfortunately seems to have gone stale: https://github.com/nextauthjs/next-auth/pull/5449 .

Reason this is all relevant is because, I'm not entire sure if using next-auth is the correct route to take. Given the issues in the past & those issuing being breaking in terms of how the codebase is written. I think what I may do is look into an alternative & follow up with @EricWeese about how he's doing auth so, I don't negate his progress. 

@aimiisme

**Comment by Sanjay-B** [comment]
Fixed as of https://github.com/KSU-Google-DSC/Webapp/commit/6257efad258e79cdb2e6c15d06efb590f5f35f84 . I pushed it to your branch. I haven't looked at this stuff in a while so, it was tripping me up but, I think next-auth does some weird injecting thing that adds ``session`` to the App component's prop. So essentially, you were creating two session states & it might have no realized that & defaulted to that error. I wish they had a more descriptive error than that. Would probably be easier to figure out. Took me a solid 20 minutes of searching. I am going to close this since it seems like it's fixed but, feel free to reopen if need be.
